feat: Run arm64 builds on arm runner
famedly/github-workflows pull request #40
Opened 2024-08-14 13:34 UTC by emgrav

2024-08-14 13:42 UTC, jcgruenhage requested changes
this means that everything we run would now move to the expensive 16 core runners. Could we make that configurable and default to the free runners instead?

2024-08-14 14:06 UTC, emgrav commented
@jcgruenhage Regrettably there is no `arm-latest` yet, afaict github plans to add this at some point this year. Would using `ubuntu-latest` and a named 4 or 8 core arm runner work?

2024-08-14 14:18 UTC, jcgruenhage commented
Sounds like a good alternative, yeah.

2025-01-30 09:26 UTC, CherryKitten approved these changes
looks good

2025-01-30 09:28 UTC, merged